version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    build: ./db
    ports:
      - "5000:5000"
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=db
  web:
    build: ./web
    command: bash -c "chmod +x ./wait-for-it.sh && chmod +x ./server.js && ./wait-for-it.sh --timeout=0 --host=$${WAIT_HOST} --port=$${WAIT_PORT} -- node_modules/.bin/nodemon ./server.js"]
    environment:
      - WAIT_HOST=db
      - WAIT_PORT=5432
    depends_on:
      - db
    volumes:
      - ./web:/usr/src/app
    ports:
     - "49161:8081"